
package com.curso.servicio.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 3.1.5
 * Mon Mar 07 19:52:55 CET 2016
 * Generated source version: 3.1.5
 */

@XmlRootElement(name = "getHistoricoGasolinera", namespace = "http://servicio.curso.com/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "getHistoricoGasolinera", namespace = "http://servicio.curso.com/")

public class GetHistoricoGasolinera {

    @XmlElement(name = "arg0")
    private java.lang.Integer arg0;

    public java.lang.Integer getArg0() {
        return this.arg0;
    }

    public void setArg0(java.lang.Integer newArg0)  {
        this.arg0 = newArg0;
    }

}

