
package com.curso.servicio.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 3.1.5
 * Mon Mar 07 19:52:55 CET 2016
 * Generated source version: 3.1.5
 */

@XmlRootElement(name = "listarPorciudad", namespace = "http://servicio.curso.com/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "listarPorciudad", namespace = "http://servicio.curso.com/")

public class ListarPorciudad {

    @XmlElement(name = "ciudad")
    private java.lang.String ciudad;

    public java.lang.String getCiudad() {
        return this.ciudad;
    }

    public void setCiudad(java.lang.String newCiudad)  {
        this.ciudad = newCiudad;
    }

}

